#!/usr/bin/env bash

# Make neovim the default editor
export EDITOR='nvim';

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr
export PYTHONIOENCODING='UTF-8';

# Prefer US English and use UTF-8
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Highlight section titles in manual pages
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page
export MANPAGER='less -X';

# Hide the “default interactive shell is now zsh” warning on macOS
export BASH_SILENCE_DEPRECATION_WARNING=1;

# update path for Make > 3.8.1
# gnubin path since make was installed as "gmake"
export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"

# coursier
export PATH="$PATH:/Users/brianrice/Library/Application Support/Coursier/bin"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# jenv
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

# gcc-arm-none-eabi for QMK
export PATH="/Applications/ARM/bin:$PATH"

# Holy shit homebrew is annoying
export HOMEBREW_NO_AUTO_UPDATE=1

# direnv
eval "$(direnv hook bash)"
